### ISSUE TITLE
Try Twirp gateway implemetation

### ISSUE THREAD

**Issue by dehwyy** [dehwyy/mafuyu#6]
### According to [Twirp](https://github.com/twitchtv/twirp) docs, it runs on `HTTP v1.1` which compatible with web (If I'm not mistaking).
- `Twirp` should be used instead of plain `Grpc` (which is not compatible with web by default as it uses  `HTTP v2`)
- As `Twirp` is written on `Go` and has only 17 stars for `Rust` implementation, the `gateway` should be written in `Go`

**Comment by Waypo1nt1** [comment]
### `Twirp` implementation is not necessary!
- Same can be achieved using `grpc-web`.

**Comment by dehwyy** [comment]
Just used `@protobuf-ts/grpcweb-transport` for grpc-web + `tonic_web`
